### ISSUE TITLE
Value Error in training.py

### ISSUE THREAD

**Issue by NatOregon** [RsGoksel/Mechopter#1]
When i try to execute train.py file, this error occures

ValueError: could not broadcast input array from shape (7,) into shape (6,)

Original code is working well but when i try to tweak some variable, this error comes up everytime. Is it variable or environmental issue ? 
 
![Error](https://github.com/RsGoksel/Mechopter/assets/148886112/0387dd2c-e097-45d6-9aaf-e697ffe6c029)

**Comment by RsGoksel** [comment]
Either you've changed self.observation_space in init method, or you've changed the array yields from get_obs method. Would you check if those are same size ?
This error indicates that you have different shape of observations.

self.observation_space = (.. .. .. , shape = (,X)
self. get_obs() -> np.array()

X should equal len(np.array())
